### ISSUE TITLE
Too restrictive owner/delegate check on transfer execute

### ISSUE THREAD

**Issue by febo** [wen-community/wen-new-standard#16]
The requirement that `owner_delegate` account is a `SystemAccount` prevents a transfer authorized by a PDA account. Most likely this constraint will need to be relaxed to allow programs to transfer NFTs:

https://github.com/wen-community/wen-new-standard/blob/main/programs/wen-new-standard/src/instructions/royalty/execute.rs#L24

**Comment by Bhargavamacha** [comment]
makes sense, will update

**Comment by balmy-gazebo** [comment]
Completed in PR 17
